### ISSUE TITLE
not compatible with latest zotero

### ISSUE THREAD

**Issue by yzliu01** [dcartertod/zotero-plugins#18]
Is this a common issue recently to use `ZoteroPreview.xpi` on Win10 machine?

![image](https://user-images.githubusercontent.com/93487645/178530680-02575303-c9fe-40fb-a937-a3d0887faaa5.png)

**Comment by dabuechner** [comment]
I am facing the same issue with version 6.0.13. Is there any workaround available?

**Comment by dcartertod** [comment]
Will need to research

**Comment by dcartertod** [comment]
What OS?

**Comment by dcartertod** [comment]
I don't know that it will help, since I'm a bit mystified by the error, but I just released a new version.

If you rename the .xpi to .zip does that make a difference? Does it open as a .zip file?

**Comment by dabuechner** [comment]
Unfortunately, both attempts did not work. I still get the same error message. 
I am using Win 10 Enterprise LTSC x64 on a company notebook. I will try your plugin on my personal computer later. Lets see, if it works there.

**Comment by dcartertod** [comment]
FYI - the problem appears to be that I haven't set up this repository in quite the right way. Please make sure to download Zotero Preview from either the Releases page or [from this link](https://github.com/dcartertod/zotero-plugins/raw/main/ZoteroPreview.xpi)

**Comment by WMAM** [comment]
If it helps, I have no problems with the plugin. It auto-updated today with no problems.
Windows 10; Zotero 6.0.14.beta1

**Comment by dcartertod** [comment]
I released a couple of updates and cleaned up the GitHub repository itself. I think it should be good now.

**Comment by dabuechner** [comment]
I downloaded version 0.1.16 from the release page and it works like a charm. That's exactly what I was looking for.
Thank you!
